const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/brave',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:3000')?r.continue():r.abort());
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const result={checks:[],errors};
 const out='/tmp/nucaloric-inspection/motion';fs.mkdirSync(out,{recursive:true});
 async function check(name,fn){try{await fn();result.checks.push({name,pass:true})}catch(e){result.checks.push({name,pass:false,error:e.message})}}
 function assert(v,s){if(!v)throw Error(s)}
 await page.goto('http://127.0.0.1:3000/index.html',{waitUntil:'domcontentloaded'});
 await page.locator('.motion-build').scrollIntoViewIfNeeded();await page.waitForTimeout(950);
 await check('Headline settles into readable DOM text',async()=>{assert(await page.locator('.motion-headline').innerText()==='Build\nsomething\nreal.','Heading differs');assert(await page.locator('.motion-build').evaluate(e=>e.classList.contains('motion-visible')),'No entrance')});
 await check('Silent visual plays only when visible',async()=>{await page.waitForFunction(()=>!document.querySelector('#possibilitiesVisual').paused);assert(await page.locator('#possibilitiesVisual').evaluate(v=>v.muted),'Not muted')});
 await page.screenshot({path:path.join(out,'home-desktop.png')});
 await check('Visual pause persists across visibility changes',async()=>{await page.locator('.motion-visual-toggle').click();assert(await page.locator('#possibilitiesVisual').evaluate(v=>v.paused),'Not paused');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(150);await page.locator('.motion-build').scrollIntoViewIfNeeded();await page.waitForTimeout(200);assert(await page.locator('#possibilitiesVisual').evaluate(v=>v.paused),'User pause lost')});
 await check('Visual stops offscreen',async()=>{await page.locator('.motion-visual-toggle').click();await page.waitForFunction(()=>!document.querySelector('#possibilitiesVisual').paused);await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(180);assert(await page.locator('#possibilitiesVisual').evaluate(v=>v.paused),'Offscreen video playing')});
 await check('Stripe navigation completes without the old delay',async()=>{const start=Date.now();await Promise.all([page.waitForURL('**/hosting.html'),page.evaluate(()=>document.querySelector('.nav-tabs a[href="hosting.html"]').click())]);assert(Date.now()-start<700,'Navigation too slow');await page.waitForTimeout(360);assert(!await page.locator('html').evaluate(e=>e.classList.contains('transition-arrival')),'Arrival class stuck')});
 await page.waitForTimeout(3400);await page.screenshot({path:path.join(out,'hosting-desktop.png')});
 await check('Walkthrough reaches code after one entrance',async()=>{assert(await page.locator('[data-workspace-demo]').getAttribute('data-demo-stage')==='2','Not code step');assert((await page.locator('[data-demo-code]').innerText()).includes('$ npm run dev'),'Missing typed code')});
 await check('Walkthrough keyboard controls select readable examples',async()=>{await page.locator('[data-demo-step="1"]').focus();await page.keyboard.press('Enter');assert(await page.locator('[data-demo-step="1"]').getAttribute('aria-pressed')==='true','Step not selected');assert((await page.locator('[data-demo-code]').innerText()).includes('Website, API'),'Wrong content')});
 await check('Selected walkthrough step survives scrolling',async()=>{await page.locator('#workspaceBuilder').scrollIntoViewIfNeeded();await page.waitForTimeout(180);await page.locator('[data-workspace-demo]').scrollIntoViewIfNeeded();await page.waitForTimeout(180);assert(await page.locator('[data-workspace-demo]').getAttribute('data-demo-stage')==='1','Manual choice lost')});
 await check('Replay begins the example again',async()=>{await page.locator('[data-demo-replay]').click();assert(await page.locator('[data-workspace-demo]').getAttribute('data-demo-stage')==='0','Not reset')});
 await page.goto('http://127.0.0.1:3000/registry.html',{waitUntil:'domcontentloaded'});await page.waitForTimeout(200);
 await check('Depth sphere animates in the shared canvas',async()=>{const a=await page.locator('#capabilitySculpture').evaluate(c=>c.toDataURL());await page.waitForTimeout(250);const b=await page.locator('#capabilitySculpture').evaluate(c=>c.toDataURL());assert(a!==b,'Sphere static')});
 await page.screenshot({path:path.join(out,'registry-desktop.png')});
 await page.emulateMedia({reducedMotion:'reduce'});
 await check('Reduced motion stops the Registry sphere',async()=>{await page.waitForTimeout(100);const a=await page.locator('#capabilitySculpture').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);assert(a===await page.locator('#capabilitySculpture').evaluate(c=>c.toDataURL()),'Sphere moving')});
 await page.goto('http://127.0.0.1:3000/index.html',{waitUntil:'domcontentloaded'});await page.locator('.motion-build').scrollIntoViewIfNeeded();await page.waitForTimeout(200);
 await check('Reduced motion shows static headline and visual poster',async()=>{assert(await page.locator('#possibilitiesVisual').evaluate(v=>v.paused),'Video autoplay under reduced motion');assert(await page.locator('.motion-word>span').first().evaluate(e=>getComputedStyle(e).transform)==='none','Headline transformed')});
 await check('Reduced motion stops the hero wave',async()=>{await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(100);const a=await page.locator('#heroWave').evaluate(c=>c.toDataURL());await page.waitForTimeout(200);assert(a===await page.locator('#heroWave').evaluate(c=>c.toDataURL()),'Hero moving')});
 await check('Reduced-motion navigation remains immediate',async()=>{const start=Date.now();await Promise.all([page.waitForURL('**/hosting.html'),page.evaluate(()=>document.querySelector('.nav-tabs a[href="hosting.html"]').click())]);assert(Date.now()-start<400,'Delayed navigation');assert(!await page.locator('[data-workspace-demo]').evaluate(e=>e.classList.contains('demo-playing')),'Demo autoplay')});
 await check('Reduced-motion controls reveal the complete code',async()=>{await page.locator('[data-demo-step="2"]').click();assert((await page.locator('[data-demo-code]').innerText()).includes('$ git status'),'Code incomplete')});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:390,height:844});
 for(const name of ['index','hosting','registry']){await page.goto('http://127.0.0.1:3000/'+name+'.html',{waitUntil:'domcontentloaded'});if(name==='index')await page.locator('.motion-build').scrollIntoViewIfNeeded();if(name==='hosting')await page.locator('[data-workspace-demo]').scrollIntoViewIfNeeded();await page.waitForTimeout(900);await page.screenshot({path:path.join(out,name+'-mobile.png')});await check(name+' fits mobile width',async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow'))}
 const plain=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const nojs=await plain.newPage();await nojs.goto('http://127.0.0.1:3000/index.html',{waitUntil:'domcontentloaded'});
 await check('Core message remains visible without JavaScript',async()=>{assert(await nojs.locator('.motion-headline').isVisible(),'Headline hidden');assert(await nojs.locator('.motion-word>span').first().evaluate(e=>getComputedStyle(e).opacity)==='1','Hidden words')});
 await check('No uncaught page errors',async()=>assert(errors.length===0,errors.join('; ')));
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();if(result.checks.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
