const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/brave',headless:true});let result={pages:[],tests:[]};const ctx=await b.newContext();await ctx.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:3000')?r.continue():r.abort());const p=await ctx.newPage();p.setDefaultTimeout(5000);
for(const width of [1440,390]){await p.setViewportSize({width,height:1000});for(const name of ['launchpad','registry']){let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:3000/${name}.html`,{waitUntil:'domcontentloaded'});await p.waitForTimeout(450);result.pages.push({name,width,errors,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});await p.screenshot({path:`/tmp/${name}-after-${width}.png`,fullPage:true});p.removeAllListeners('pageerror')}}
async function test(name,fn){try{await fn();result.tests.push({name,pass:true})}catch(e){result.tests.push({name,pass:false,error:e.message})}}
await p.setViewportSize({width:1440,height:1000});await p.goto('http://127.0.0.1:3000/launchpad.html',{waitUntil:'domcontentloaded'});
await test('Blank identity blocked',async()=>{await p.locator('#launchName').fill('');await p.locator('#builderNext').click();if(!await p.locator('#builderError').innerText())throw Error('No validation');await p.locator('#launchName').fill('Nova Test')});
await test('Draft survives reload',async()=>{await p.locator('#launchTicker').fill('TEST');await p.reload({waitUntil:'domcontentloaded'});if(await p.locator('#launchTicker').inputValue()!=='TEST')throw Error('Draft lost')});
await test('Rewards apply and review',async()=>{await p.locator('[data-step="4"]').click();await p.locator('[data-ai-apply="rewards"]').click();if(await p.locator('#launchRewards').inputValue()!=='15')throw Error('Rewards not applied');await p.locator('[data-step="7"]').click();if(await p.locator('#reviewRewards').innerText()!=='15%')throw Error('Review stale')});
await test('Complete selections in review',async()=>{await p.locator('[data-step="2"]').click();await p.locator('#launchSupply').fill('123456');await p.locator('#launchVest').selectOption({label:'365 DAYS'});await p.locator('[data-step="3"]').click();await p.locator('#launchLock').selectOption({label:'90 DAYS'});await p.locator('[data-step="5"]').click();await p.locator('.dist-card').nth(1).click();await p.locator('[data-step="7"]').click();if(await p.locator('#reviewSupply').innerText()!=='123,456')throw Error('Supply mismatch');if(await p.locator('#reviewVest').innerText()!=='365 DAYS')throw Error('Vesting mismatch');if(await p.locator('#reviewLock').innerText()!=='90 DAYS')throw Error('Lock mismatch');if((await p.locator('#reviewDistribution').innerText()).includes('REWARD RAIL'))throw Error('Distribution stale')});
await test('Blueprint download',async()=>{await p.locator('[data-step="8"]').click();const [download]=await Promise.all([p.waitForEvent('download'),p.locator('#builderNext').click()]);await download.saveAs('/tmp/nucaloric-inspection/test-blueprint.json');const data=JSON.parse(fs.readFileSync('/tmp/nucaloric-inspection/test-blueprint.json'));if(data.fields.launchRewards!=='15'||!data.prototype)throw Error('Wrong blueprint')});
await p.goto('http://127.0.0.1:3000/registry.html',{waitUntil:'domcontentloaded'});
await test('Registry search and empty reset',async()=>{await p.locator('#registrySearch').fill('buy back');if(await p.locator('.registry-group .cap-card:visible').count()!==1)throw Error('Search mismatch');await p.locator('#registrySearch').fill('zzzznomatches');if(!await p.locator('#registryEmpty').isVisible())throw Error('Missing empty state');await p.locator('#registryReset').click();if(await p.locator('.registry-group .cap-card:visible').count()!==49)throw Error('Reset mismatch')});
await test('Offline filter',async()=>{await p.locator('[data-reg-filter="offline"]').click();if(await p.locator('.registry-group .cap-card:visible').count()!==6)throw Error('Offline mismatch')});
await test('Keyboard card opens named drawer',async()=>{const card=p.locator('.cap-card:visible').first();await card.focus();await p.keyboard.press('Enter');if(!await p.locator('.capability-drawer.open').isVisible())throw Error('No drawer');if(await p.locator('#capabilityDrawerContent h2').innerText()!=='Event radar')throw Error('Missing title');await p.keyboard.press('Escape')});
await test('Atlas links to category',async()=>{await p.locator('[data-reg-filter="all"]').click();await p.locator('.atlas-node[href="#treasury"]').click();if(!p.url().endsWith('#treasury'))throw Error('Anchor failed')});
await p.emulateMedia({reducedMotion:'reduce'});await p.goto('http://127.0.0.1:3000/registry.html',{waitUntil:'domcontentloaded'});await test('Reduced motion stops atlas',async()=>{await p.waitForTimeout(150);const a=await p.locator('#capabilityAtlas').evaluate(c=>c.toDataURL());await p.waitForTimeout(150);const z=await p.locator('#capabilityAtlas').evaluate(c=>c.toDataURL());if(a!==z)throw Error('Atlas still moving')});
fs.writeFileSync('/tmp/nucaloric-inspection/refresh-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
